name = "rsw"
version = "0.1.0"

#! time interval for file changes to trigger wasm-pack build, default `50` milliseconds
interval = 50

#! link
#! npm link @see https://docs.npmjs.com/cli/v8/commands/npm-link
#! yarn link @see https://classic.yarnpkg.com/en/docs/cli/link
#! pnpm link @see https://pnpm.io/cli/link
#! The link command will only be executed if `[[crates]] link = true`
#! cli: `npm` | `yarn` | `pnpm`, default is `npm`
cli = "pnpm"

#! ---------------------------

#! rsw new <name>
[new]
using = "wasm-pack"

#! ################# NPM Package #################

[[crates]]
#! npm package name (path: $ROOT/@rsw/hello)
name = "@yuehaiteam/cocogoat-lib"
#! default is `.`
root = "./lib"
#! default is `pkg`
out-dir = "pkg"
#! target: bundler | nodejs | web | no-modules, default is `web`
target = "web"
#! run `npm link`: `true` | `false`, default is `false`
link = false